export const COMPLAINTS_INIT = [
  {
    id: 'C-2024-001',
    type: 'Physical Ragging',
    severity: 'High',
    status: 'escalated',
    college: 'IIT Delhi',
    dept: 'CSE',
    year: '2nd Year',
    date: '2024-12-01',
    desc: 'Senior students forced freshers to perform humiliating tasks in the hostel corridor after midnight. Three students were involved in the incident.',
    escalationLevel: 3,
    assignedTo: 'Anti-Ragging Committee',
    anonymous: true,
    timeline: [
      { event: 'Complaint filed', time: 'Dec 1, 10:42 AM', color: 'blue' },
      { event: 'University notified', time: 'Dec 1, 11:00 AM', color: 'blue' },
      { event: 'Escalated to committee', time: 'Dec 2, 09:00 AM', color: 'amber' },
      { event: 'Police loop-in initiated', time: 'Dec 3, 02:00 PM', color: 'red' },
    ],
  },
  {
    id: 'C-2024-002',
    type: 'Verbal Abuse',
    severity: 'Medium',
    status: 'investigating',
    college: 'NIT Trichy',
    dept: 'Mechanical',
    year: '1st Year',
    date: '2024-12-03',
    desc: 'Repeated verbal harassment by senior batch during lab sessions. Victim reports feeling unsafe.',
    escalationLevel: 2,
    assignedTo: 'Dean of Students',
    anonymous: true,
    timeline: [
      { event: 'Complaint filed', time: 'Dec 3, 08:15 AM', color: 'blue' },
      { event: 'Under investigation', time: 'Dec 3, 10:00 AM', color: 'amber' },
    ],
  },
  {
    id: 'C-2024-003',
    type: 'Mental Harassment',
    severity: 'High',
    status: 'pending',
    college: 'BITS Pilani',
    dept: 'EEE',
    year: '1st Year',
    date: '2024-12-04',
    desc: 'Student forced to do assignments of seniors under threat of public humiliation. Ongoing for 3 weeks.',
    escalationLevel: 1,
    assignedTo: '—',
    anonymous: true,
    timeline: [
      { event: 'Complaint filed', time: 'Dec 4, 04:30 PM', color: 'blue' },
    ],
  },
  {
    id: 'C-2024-004',
    type: 'Physical Ragging',
    severity: 'High',
    status: 'police',
    college: 'IIT Bombay',
    dept: 'Civil',
    year: '1st Year',
    date: '2024-11-28',
    desc: 'Student hospitalised after severe ragging incident. Police case registered under IPC 107.',
    escalationLevel: 4,
    assignedTo: 'Maharashtra Police',
    anonymous: false,
    timeline: [
      { event: 'Complaint filed', time: 'Nov 28, 01:00 AM', color: 'blue' },
      { event: 'Hospital admission logged', time: 'Nov 28, 07:00 AM', color: 'red' },
      { event: 'Police case filed', time: 'Nov 28, 11:30 AM', color: 'red' },
      { event: 'FIR #MH-2024-4821 registered', time: 'Nov 28, 03:00 PM', color: 'indigo' },
    ],
  },
  {
    id: 'C-2024-005',
    type: 'Psychological Pressure',
    severity: 'Low',
    status: 'resolved',
    college: 'VIT Vellore',
    dept: 'BioTech',
    year: '2nd Year',
    date: '2024-11-30',
    desc: 'Seniors pressuring juniors to buy items and run errands. Matter resolved through counselling.',
    escalationLevel: 1,
    assignedTo: 'Counselling Cell',
    anonymous: true,
    timeline: [
      { event: 'Complaint filed', time: 'Nov 30, 09:00 AM', color: 'blue' },
      { event: 'Counselling session held', time: 'Dec 1, 02:00 PM', color: 'green' },
      { event: 'Resolved', time: 'Dec 2, 05:00 PM', color: 'green' },
    ],
  },
  {
    id: 'C-2024-006',
    type: 'Cyberbullying',
    severity: 'Medium',
    status: 'investigating',
    college: 'Jadavpur University',
    dept: 'IT',
    year: '1st Year',
    date: '2024-12-05',
    desc: 'Victim receiving threatening WhatsApp messages from unknown numbers linked to senior batch.',
    escalationLevel: 2,
    assignedTo: 'Anti-Ragging Committee',
    anonymous: true,
    timeline: [
      { event: 'Complaint filed', time: 'Dec 5, 12:00 PM', color: 'blue' },
      { event: 'Digital forensics requested', time: 'Dec 5, 04:00 PM', color: 'amber' },
    ],
  },
];

export const USERS_INIT = [
  { id: 'U001', name: 'Arjun Mehta',   role: 'Student',           college: 'IIT Delhi',         status: 'active',    joined: 'Aug 2024', complaints: 1 },
  { id: 'U002', name: 'Priya Sharma',  role: 'Admin',             college: 'NIT Trichy',         status: 'active',    joined: 'Jan 2024', complaints: 0 },
  { id: 'U003', name: 'Rahul Verma',   role: 'Student',           college: 'BITS Pilani',        status: 'suspended', joined: 'Aug 2024', complaints: 2 },
  { id: 'U004', name: 'Sneha Nair',    role: 'Committee Member',  college: 'IIT Bombay',         status: 'active',    joined: 'Mar 2023', complaints: 0 },
  { id: 'U005', name: 'Kiran Patel',   role: 'Student',           college: 'VIT Vellore',        status: 'active',    joined: 'Aug 2024', complaints: 1 },
  { id: 'U006', name: 'Ananya Roy',    role: 'Dean',              college: 'Jadavpur University',status: 'active',    joined: 'Jun 2020', complaints: 0 },
  { id: 'U007', name: 'Dev Khanna',    role: 'Student',           college: 'IIT Delhi',          status: 'flagged',   joined: 'Aug 2024', complaints: 3 },
];

export const ALERTS_INIT = [
  { id: 1, level: 'critical', title: 'Police case active — C-2024-004', desc: 'IIT Bombay complaint has escalated to law enforcement. Requires daily monitoring.', time: '2 hours ago', color: 'red' },
  { id: 2, level: 'warning',  title: 'Escalation deadline in 6h — C-2024-003', desc: 'BITS Pilani complaint unassigned. Auto-escalation will trigger at 22:30.', time: '5 hours ago', color: 'amber' },
  { id: 3, level: 'info',     title: 'New complaint submitted — C-2024-006', desc: 'Cyberbullying complaint from Jadavpur University requires initial review.', time: '8 hours ago', color: 'blue' },
  { id: 4, level: 'warning',  title: 'User U007 flagged for suspicious activity', desc: '3 complaints filed within 30 days. Possible misuse of portal detected.', time: '1 day ago', color: 'amber' },
  { id: 5, level: 'info',     title: 'Monthly report generated', desc: 'December 2024 anti-ragging report ready for download.', time: '2 days ago', color: 'blue' },
];

export const LOGS_INIT = [
  { time: '2024-12-05 14:32:01', level: 'info',  msg: 'Complaint C-2024-006 submitted via anonymous portal',             actor: 'system' },
  { time: '2024-12-05 14:30:15', level: 'warn',  msg: 'Escalation timer triggered for C-2024-003 — 48h deadline reached', actor: 'escalation-engine' },
  { time: '2024-12-05 12:01:44', level: 'info',  msg: 'User U007 (Dev Khanna) profile flagged by fraud detector',        actor: 'fraud-engine' },
  { time: '2024-12-04 18:20:09', level: 'error', msg: 'Email notification failed for dean@nittr.ac.in — SMTP timeout',   actor: 'notification-service' },
  { time: '2024-12-04 09:15:33', level: 'info',  msg: 'Admin login: admin@safecampus.in from 203.145.11.42',             actor: 'auth' },
  { time: '2024-12-03 22:44:11', level: 'warn',  msg: 'Duplicate submission attempt detected for IP 192.168.1.45',       actor: 'rate-limiter' },
  { time: '2024-12-03 10:00:00', level: 'info',  msg: 'C-2024-002 status updated: pending → investigating',              actor: 'admin-panel' },
  { time: '2024-12-02 09:05:22', level: 'info',  msg: 'Scheduled escalation job ran — 1 complaint elevated',             actor: 'scheduler' },
  { time: '2024-12-01 11:00:00', level: 'info',  msg: 'C-2024-001 assigned to anti-ragging committee',                   actor: 'admin-panel' },
  { time: '2024-11-30 17:45:00', level: 'info',  msg: 'C-2024-005 marked resolved by counselling cell',                  actor: 'admin-panel' },
];